### ISSUE TITLE
HybPiper version

### ISSUE THREAD

**Issue by SethMusker** [LarsNauheimer/HybPhaser#1]
Hi Lars,

Could you please include in the Readme a reference to which version/release of HybPiper was used? In case there are any future changes on that side that might mess with things.

Looking forward to using this! 

Cheers,
Seth

**Comment by SethMusker** [comment]
...and, for that matter, samtools, bcftools and bwa versions.

**Comment by LarsNauheimer** [comment]
Hi Seth, 
Thanks for the comment! I added the version info.
I will also upload soon a version that has several bug fixes and minor improvements. 
Hopefully the workflow is helpful for yoour analyses. Let me know if you run into any issues!
Cheers, 
Lars

**Comment by SethMusker** [comment]
Awesome, thanks! Will do :)
