### ISSUE TITLE
Consensus sequence files all empty 

### ISSUE THREAD

**Issue by bfauskee** [LarsNauheimer/HybPhaser#18]
Trying to run the first script:
`bash 1_generate_consensus_sequences.sh -n namelist.txt -p hybpiper_output/ -o ./hybphaser -t 8`
and all the consensus sequence files are empty. Seems like the script is finding my reads and contigs and generating BAMS and VCFs.

**Comment by erika-r-moore** [comment]
I am having the same issue. Is there a solution to resolve this?
